version: '3'
services:
        opal:
                build: .
                #image: obiba/opal:resources
                ports:
                        - "8843:8443"
                        - "8880:8080"
                links:
                        - rserver
                        - mongo
                        - mysqldata
                environment:
                        - JAVA_OPTS=-Xms1G -Xmx8G -XX:+UseG1GC
                        - OPAL_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - MYSQLDATA_HOST=mysqldata
                        - MYSQLDATA_USER=opal
                        - MYSQLDATA_PASSWORD=password
                        - RSERVER_HOST=rserver
                volumes:
                        - /tmp/opal:/srv
        mongo:
                image: mongo
        mysqldata:
                image: mysql
                environment:
                        - MYSQL_DATABASE=opal
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=opal
                        - MYSQL_PASSWORD=password
        rserver:
                image: obiba/opal-rserver:snapshot
